update: support registering device-specific update handlers
gokrazy/gokrazy pull request #102
Opened 2021-12-29 05:08 UTC by anupcshan

Useful to update devices which expect blobs at fixed locations

Related to #101

2021-12-31 10:12 UTC, stapelberg requested changes
Thanks for your PR!

I think it’d be better to only offer a function that sets up the extra update handlers based on the device type, instead of offering a function that allows to set arbitrary update handlers.

E.g., how about `gokrazy.SetupDeviceSpecifics()`, taking a constant identifying the system (e.g. odroid)?

2022-01-01 07:06 UTC, anupcshan commented
> Thanks for your PR!
> 
> I think it’d be better to only offer a function that sets up the extra update handlers based on the device type, instead of offering a function that allows to set arbitrary update handlers.
> 
> E.g., how about `gokrazy.SetupDeviceSpecifics()`, taking a constant identifying the system (e.g. odroid)?

Hmmm, I'm trying to figure out where gokrazy process would get the list of device specific handlers, in that case.
As it is implemented now, `gokr-packer` is responsible for parsing the device manifest and passing along handler information to `gokrazy` via `main()` in the generated `init,go`.

There are a few other ways to achieve this:
1. Store relevant config in some kind of `map[deviceType]deviceDetails` in `gokrazy/gokrazy`. This way, we can get rid of the device manifest file altogether and pass along `mbr-but-not-gpt` and "device type" as flags to `gokr-packer`. Makes it easy to call `gokrazy.SetupDeviceSpecifics(deviceType)` via `init.go` in this approach. This is the simplest way to implement it. Sounds like this is what you're suggesting.
2. Keep the device manifest around, dump the manifest file in the root image and have it parsed and acted on by `gokrazy`. Instead of passing along arbitrary update handlers, `gokrazy` just reads the (optional) manifest on start and registers appropriate handlers.

What do you think?

2022-01-04 09:11 UTC, stapelberg commented
> Hmmm, I'm trying to figure out where gokrazy process would get the list of device specific handlers, in that case.

What does https://pkg.go.dev/github.com/gokrazy/gokrazy#Model return on the odroid? (You can see the detected model in the gokrazy web interface.)

If the odroid devices report their model correctly, that might be the easiest way.

Keeping a map of device specifics inside gokrazy (option 1 in your reply) sounds preferable over option 2 to me.

2022-01-04 17:09 UTC, anupcshan commented
> > Hmmm, I'm trying to figure out where gokrazy process would get the list of device specific handlers, in that case.
> 
> What does https://pkg.go.dev/github.com/gokrazy/gokrazy#Model return on the odroid? (You can see the detected model in the gokrazy web interface.)
> 
> If the odroid devices report their model correctly, that might be the easiest way.

They return "Hardkernel Odroid HC1" (from https://github.com/torvalds/linux/blob/c9e6606c7fe92b50a02ce51dda82586ebdf99b48/arch/arm/boot/dts/exynos5422-odroidhc1.dts#L14). That's unique enough to identify this device type.

> 
> Keeping a map of device specifics inside gokrazy (option 1 in your reply) sounds preferable over option 2 to me.

Yep, I've gone ahead and stored the device configs in `gokrazy/internal` - https://github.com/gokrazy/internal/pull/9. Its not in `gokrazy/gokrazy` because `gokr-packer` also needs to reference this device config while generating disk image/updating.

Let me make the change to use `gokrazy.Model` as the device type key (and rename that to device model).

2022-01-05 05:02 UTC, anupcshan commented
OK, PRs for all relevant changes are ready now (in dependency order):
1. https://github.com/gokrazy/internal/pull/9 has the device config itself with some validation checks
2. This PR calls `gokrazy.SetupDeviceSpecifics` in `SuperviseServices` - uses `gokrazy.Model` to automatically register device-specific stuff.
3. https://github.com/gokrazy/tools/pull/28 to do the gokr-packer bits.

Each PR depends on the one before it (needs a go mod upgrade to pick up previous change).

I use https://github.com/anupcshan/odroidbake/blob/main/Makefile to manage a test installation.

2022-01-09 15:03 UTC, stapelberg reviewed
This is looking much better now!

2022-01-09 15:03 UTC, stapelberg commented on update.go
> +		http.HandleFunc(fmt.Sprintf("/update/%s", extraUpdateHandler.name), nonConcurrentLimitedUpdateHandler(extraUpdateHandler.device, extraUpdateHandler.offset, extraUpdateHandler.maxLength))
I think an extra level of hierarchy would be good in the paths. How about `/update/device-specific/<name>`?

2022-01-09 15:03 UTC, stapelberg commented on update.go
> +	log.Printf("setting up device-specific handlers for '%s'", modelName)
Use %q instead of '%s' here

2022-01-09 15:03 UTC, stapelberg commented on update.go
> +	log.Printf("setting up device-specific handlers for '%s'", modelName)
Make it “device-specific update handlers” instead of “device-specific handlers”

2022-01-09 15:03 UTC, stapelberg commented on update.go
> +type ExtraUpdateHandler struct {
Why is this type exported? It doesn’t need to be, right? Can you change it to `extraUpdateHandler` (lower-case e)?

2022-01-11 19:20 UTC, stapelberg approved these changes

2022-01-11 19:21 UTC, stapelberg commented
This PR is good to go! Can you remove the `replace` directive in go.mod and pull in the latest `gokrazy/internal` please?

2022-01-11 19:23 UTC, anupcshan commented
> This PR is good to go! Can you remove the `replace` directive in go.mod and pull in the latest `gokrazy/internal` please?

Thanks for the thorough review! Updated.

2022-01-11 19:29 UTC, stapelberg approved these changes

2022-01-11 19:29 UTC, merged