Indicate where default password can be recovered on macOS/Darwin
gokrazy/gokrazy pull request #133
Opened 2022-05-27 11:27 UTC by damdo

The path differs for macOS/Darwin.

Related to: https://github.com/gokrazy/internal/pull/12

Note: I had to change `<code> ... </code>` into backticks to avoid strikethrough in artifacts.

![render](https://user-images.githubusercontent.com/4902157/170690643-bf951c9a-cef3-4ca5-baa4-8e558194a5fc.png)

2022-05-27 19:27 UTC, stapelberg requested changes

2022-05-27 19:27 UTC, stapelberg commented on website/content/quickstart/_index.markdown
> +  (the default password can be recovered from `~/.config/gokrazy/http-password.txt` on Linux or from `~/Library/Application\ Support/gokrazy/http-password.txt` on macoOS/Darwin)
typo: macOS

2022-05-27 21:02 UTC, damdo commented on website/content/quickstart/_index.markdown
> +  (the default password can be recovered from `~/.config/gokrazy/http-password.txt` on Linux or from `~/Library/Application\ Support/gokrazy/http-password.txt` on macoOS/Darwin)
Oops updated. Thanks.

2022-05-28 08:05 UTC, stapelberg approved these changes

2022-05-28 08:10 UTC, merged

2022-05-28 08:10 UTC, stapelberg commented
Thanks!