Add documentation page on how to get Prometheus running
gokrazy/gokrazy pull request #211
Opened 2023-07-27 23:13 UTC by Syphdias

This goes over how to install the Prometheus server on gokrazy and how
to get the web ui working since the web assets do not get built into the
prometheus binary.

2023-09-19 20:47 UTC, Syphdias commented
Hey @stapelberg, I would love to get some feedback on this.

2023-10-20 09:27 UTC, stapelberg requested changes
Sorry for the late review. I missed this thread in my inbox.

2023-10-20 09:27 UTC, stapelberg commented on website/content/packages/prometheus.md
> +        "https://github.com/prometheus/prometheus"
Remove the https:// here and below

2023-11-07 23:36 UTC, Syphdias commented
> Sorry for the late review. I missed this thread in my inbox.

No worries. As that is exactly what happened to me this time, I can relate quite well. :sweat_smile:

2023-12-12 22:49 UTC, stapelberg approved these changes

2023-12-12 22:49 UTC, merged

2023-12-12 22:49 UTC, stapelberg commented
Thank you!