Provide json status api
gokrazy/gokrazy pull request #82
Opened 2021-01-14 15:50 UTC by andig

Replaces https://github.com/gokrazy/gokrazy/pull/45

2021-01-15 15:39 UTC, stapelberg requested changes

2021-01-15 15:39 UTC, stapelberg commented on supervise.go
> +		Stopped:   s.stopped,
You’ll need to acquire stoppedMu, startedMu and processMu to safely access these fields.

Also, I think the attempt field is not currently used actually — I can only see usage of a local `attempt` variable.

2021-01-17 13:06 UTC, stapelberg requested changes

2021-01-17 13:06 UTC, stapelberg commented on status.go
> +			_, _ = fmt.Fprint(w, string(b))
Here and below: don’t use `Fprint` without specifying a format. Instead, just use `w.Write(b)` for writing out JSON.

2021-01-17 18:20 UTC, stapelberg approved these changes

2021-01-17 18:20 UTC, merged

2021-01-17 19:04 UTC, andig commented
For sake of reference, here's the actual output:

    ❯ curl -v -H "content-type: application/json" http://gokrazy:xx@evcc:8080/status\?path\=/user/brokenglass
    * Server auth using Basic with user 'gokrazy'
    > GET /status?path=/user/brokenglass HTTP/1.1
    > Host: evcc:8080
    > User-Agent: curl/7.64.1
    > Accept: */*
    > content-type: application/json
    > 
    < HTTP/1.1 200 OK
    < Access-Control-Allow-Origin: *
    < Content-Type: application/json
    < Set-Cookie: gokrazy_xsrf=615554735; Expires=Mon, 18 Jan 2021 19:02:33 GMT; HttpOnly
    < Date: Sun, 17 Jan 2021 19:02:33 GMT
    < Content-Length: 131
    < 
    {"Stopped":true,"StartTime":"1970-01-01T01:00:21.98437546+01:00","Pid":175,"Path":"/user/brokenglass","Args":["/user/brokenglass"]}